name: Test
on: [push]
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - uses: php-actions/composer@v6
      with:
        version: 2
        php_version: "8.1"
        php_extensions: intl xdebug
    - run: composer run-script test
