name: Test
on: [push]
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Setup platform
      uses: shivammathur/setup-php@v2
      with:
        php_version: "8.2"
        extensions: intl, xdebug
        tools: composer:2
        ini-values: zend.assertions=1, xdebug.mode=coverage
    - name: Install dependencies
      run: composer install
    - name: Run tests
      run: composer run-script test
